#!/bin/bash

# Author: Samuel Martins
# Date Created: 05/03/2023
# Last Modified: 05/03/2023

# Description:
# This is a bash project to automatically detect 
# and scan your local network for devices connected to it.

# Usage:
# follow the instruction is the README.md file
# ./ip-sweep
# terminal command: ip-sweep or sudo ip-sweep 


# - - - - - - - - - - Script Starts Here - - - - - - - - - - #

# Step 1. get the first octets of the network ip
ifconfig | grep "broadcast" | cut -d " " -f 10 | cut -d "." -f 1,2,3 | uniq > .octets.txt

# Step 2. Set a variable to contain the values inside the octets file
octets=$(cat .octets.txt)
chmod 444 fileName
# Step 3. create a new empty .txt files with the name of the octet
echo "" > .$octets.txt

# Step 4. Create a loop
for ip in {1..254}
    do
        ping -c 1 $octets.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" >> .$octets.txt &

done

# this simply shows whether the script added all the IPs
cat .$octets.txt | sort > .sorted_$octets.txt

# Step 5. Perorm an N-map scan
nmap -sS -iL .sorted_$octets.txt

exit 0
